This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./trab29.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file trab29.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (16 comparisons).
Generating output file trab29.acr....done (12 lines written, 0 warnings).
Output written in trab29.acr.
Transcript written in trab29.alg.
