This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./trab27.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file trab27.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file trab27.acr....done (7 lines written, 0 warnings).
Output written in trab27.acr.
Transcript written in trab27.alg.
