This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./trab25.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file trab25.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (16 comparisons).
Generating output file trab25.acr....done (13 lines written, 0 warnings).
Output written in trab25.acr.
Transcript written in trab25.alg.
