This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./trab23.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file trab23.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (34 comparisons).
Generating output file trab23.acr....done (12 lines written, 0 warnings).
Output written in trab23.acr.
Transcript written in trab23.alg.
